# Generated by Django 3.1.7 on 2021-04-03 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meghaweb', '0002_mediumimage_orderstep_questions_sectionfiveindex_sectionfourindex_sectionthreeindex_sectiontwoindex'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sectionthreeindex',
            name='dec',
        ),
        migrations.AddField(
            model_name='sectionthreeindex',
            name='dec_para_1',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='sectionthreeindex',
            name='dec_para_2',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='sectionthreeindex',
            name='dec_para_3',
            field=models.TextField(default=''),
        ),
    ]
