# Generated by Django 3.1.7 on 2021-04-03 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meghaweb', '0004_auto_20210403_1048'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SectionOneTestimonials',
            new_name='TestimonialsSectionOne',
        ),
        migrations.RenameModel(
            old_name='SectionTwoTestimonials',
            new_name='TestimonialsSectionTwo',
        ),
    ]
